### ISSUE TITLE
Improve error message when function template isn't supported

### ISSUE THREAD

**Issue by rgee0** [openfaas/openfaas-cloud#417] opened 2019-03-22 19:35 UTC
## Expected Behaviour
When a template specified in a function's `stack.yml` doesn't exist within the community cluster the error message should clearly indicate that this is the cause of the failure.

## Current Behaviour

The current status API message is:
```
Deploy to OpenFaaS
tar(s) creation failed, error : open /tmp/rgee0/faas-demo/build/helloworld/config: no such file or directory
```
The list of supported templates is available [here](https://openfaas.o6s.io/signup#templates)

## Possible Solution
Determine possible causes for makeTar() to fail and try to determine cases where the template isnt supported.

https://github.com/openfaas/openfaas-cloud/blob/6c026ed11d20bc7a4703788e0dd6073e3de3c8d9/git-tar/function/ops.go#L110-L114

## Steps to Reproduce (for bugs)

1. Create a non-supported function (python3-flask)
2. Push to an OFC enabled repo
3. Observe the status message

## Context
A user reported the issue in Slack.  Further investigation determined the cause, during the course of the investigation it was observed that the error message could be more informative.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.8.5

* Docker version `docker version` (e.g. Docker 17.0.05 ):
N/A

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
N/A

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS

* Link to your project or a code example to reproduce issue:
https://github.com/rgee0/faas-demo

**Comment by alexellis** [comment] 2019-03-23 16:14
Derek add label: help wanted

**Comment by amn41** [comment] 2019-03-24 12:30
If it isn't somewhere already, would it be possible to document somewhere how to add additional templates to an ofc installation? digging around ofc-bootstrap code it looks like need to add to `custom_templates` https://github.com/openfaas-incubator/ofc-bootstrap/commit/268d1fb547d062eb50bac53921909201d1336c61 

however not clear to me yet how/where to set that and whether i need to `reset` and rerun ofc-bootstrap

**Comment by alexellis** [comment] 2019-03-24 14:19
You can edit git-tar's environmental variables. 

Alex

**Comment by martindekov** [comment] 2019-03-25 10:18
My idea here is to get the function's `lang` field in `stack.yml` and check after fetching all the templates if folder with that name exists in the `template` folder, if it does then ok proceed, if it does not we throw error saying `error: there is no template with name ... if you with to add custom template add the git repo in file ...` or something.

**Comment by martindekov** [comment] 2019-03-25 10:22
I can work on the implementation if you agree with my approach 👍

**Comment by alexellis** [comment] 2019-03-25 10:27
Martin that sounds like a good approach. I would limit the detail on the message to something like: Template X not available at this time.

Alex

**Comment by alexellis** [comment] 2019-03-25 20:34
Looks like this is a duplicate of https://github.com/openfaas/openfaas-cloud/issues/219

**Comment by martindekov** [comment] 2019-03-26 18:06
Derek assign: me

**Comment by alexellis** [comment] 2019-03-30 13:49
@martindekov is there a PR for this yet?

**Comment by martindekov** [comment] 2019-04-01 06:45
Hey Alex, sorry I missed your comment, I was busy with university and deploying my GitLab Dev environment, I will do it in the incoming weekend

**Closed** 2019-05-14 13:57 UTC
Labels: help wanted
