### ISSUE TITLE
Tracking feature: Test mixed-case usernames

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#119] opened 2018-08-30 10:04 UTC
We need to test mixed-case usernames end-to-end including:

* of-router (using wildcard DNS)

No instructions exist for Swarm, just a YAML file for Kubernetes, so update the docs/README.md too

* UI dashboard
* GitHub push events

You'll need a second GitHub account with a MixedCase username (don't rename your existing one) and then add it to the official CUSTOMERS list or turn `validate_customers` off.

If required, please propose a fix for anything left over from the work @burtonr did.

**Comment by alexellis** [comment] 2018-08-30 10:04
Some initial testing done over at: https://github.com/openfaas/faas-cli/issues/511

**Comment by martindekov** [comment] 2018-09-03 11:29
We discussed this so the approach I am going to be taking is renaming the git owner to lower case in the palaces where the function is named i.e. name of user is `MartinDekovWat` owner stays `MartinDekovWat` but the function name in deployment will be `martindekovwat-<the_name_of_function_here>`. Should I proceed with this approach ? Do we all agree ?

**Comment by martindekov** [comment] 2018-09-03 11:30
Also the function name will be staying the same i.e. function with name `CaseSensitiveName` deployment will be `martindekovwat-CaseSensitiveName`.

**Comment by alexellis** [comment] 2018-09-03 12:33
Yes I think that's correct. Please continue with the work and we'll review the PR.

**Comment by martindekov** [comment] 2018-09-04 15:34
The PR ^ fixes names to be lowercase in function name in: `router` , `dashboard`, `github-push`

**Comment by martindekov** [comment] 2018-09-11 10:43
I just saw that comment I am on it.

**Comment by alexellis** [comment] 2018-09-13 07:46
@martindekov @burtonr what's the latest with our community cluster? I saw Martin applied for a new account using a mixed-case user.

**Comment by alexellis** [comment] 2018-09-20 12:15
Pinging @martindekov for an update

**Comment by martindekov** [comment] 2018-09-20 12:27
I am pretty confident now that we handled the cases where case sensitive username would be problem this includes:
* validate_customers
* of-router access
* dashboard acess
* dashboard with of-router access
* function creation(directly affects the of-router and dashboard)'
I think we can close the issue, I haven't been able to upload interesting/decent function with my case sensitive name on the public cloud but having tested the changes on my instance I see that the case sensitive name is not problem. 
Currently I can't think of a place where case sensitivity would be an issue correct me if I am missing something @burtonr. This is my input ATM

**Comment by alexellis** [comment] 2018-09-25 08:54
Thank you for the detailed feedback. Please go ahead and close using Derek.

@LucasRoesler since you have a case-sensitive name you'd be a perfect tester.. Could you run through the community gist and give feedback?

**Comment by martindekov** [comment] 2018-09-25 08:56
Derek close

**Comment by alexellis** [comment] 2018-09-25 09:06
@martindekov @LucasRoesler  I'm actually seeing issues here:

https://system.o6s.io/dashboard/LucasRoesler

When I click on the links for Lucas I get the wrong URL for the endpoint.. it's also wrong on the overview page. cc @kenfdev @bartsmykla @jaigouk 

Alex

**Comment by martindekov** [comment] 2018-09-25 09:40
Derek reopen

**Comment by martindekov** [comment] 2018-09-25 09:48
Now here is example function with my case sensitive user name:

https://system.o6s.io/dashboard/martindekovwat
 
The dashboard works for me, but it seems like the overview page is not working properly:

https://system.o6s.io/overview?user=martindekovwat

I need to check why is that

**Comment by martindekov** [comment] 2018-09-25 10:02
So `buildshiprun` makes functions with lowercase github username appended and the overview is mapping by `?user=GitHubName` I think this is the problem we can see that here if we write `lucasroesler` everything is working

https://system.o6s.io/overview?user=lucasroesler

the overview works fine and dashboard works fine

https://system.o6s.io/dashboard/lucasroesler

Maybe we should be taking the name from the query string and `tolower` or `equalfold` it ? I am not very familiar with javascript but the problem is the way we access the pages. @openfaas/ui ?

**Comment by LucasRoesler** [comment] 2018-09-25 11:16
sorry i missed this earlier, since i already have some function in 06s.io, is there anything specific you would like me to do right now.  The newest gist provides sealed secret instructions. Is that something we want to test now?

**Comment by alexellis** [comment] 2018-09-25 19:01
This is good to know @martindekov - perhaps we need to force the parameter to-lower in the query string / path? Feel free to raise an issue with the title "UI: Dashboard" as a prefix.

**Comment by martindekov** [comment] 2018-09-26 06:46
Ok I will do that

**Comment by burtonr** [comment] 2018-11-15 02:31
@martindekov is this issue still an issue? 

There's a chain of issues/PRs related to this now. Maybe we could close this one out?
#228 Looks to be the issue created off of Alex's comment
but that references #315 as the continuation

Just looking to clean up a bit

**Comment by martindekov** [comment] 2018-11-15 08:33
Hello @burtonr 

I think this is issue opened for general discussion regarding case sensitivity and the #315 is for specific problem. Currently we still have general problem with case sensitivity unless #315 is merged. I think it would be a good idea if we ping Swarvanu to close this along with #315 when PR with the fix is merged.

cc @s8sg

**Comment by alexellis** [comment] 2018-11-26 20:01
Thanks both for chasing this up. If we don't hear from @s8sg tomorrow, then can one of you take ownership and move this forward? Mixed-case usernames appear to be quite common on GitHub so we don't want to exclude those people from getting a good user-experience.

**Comment by s8sg** [comment] 2018-11-27 05:48
Hello @alexellis @martindekov 
I spend quite a time to create my environment with the latest code to test although I'm unable to do so
I understand the issue on priority therefor please go ahead with the fix. I'll pick something else

**Closed** 2019-02-06 12:37 UTC
Labels: priority/high

**Comment by alexellis** [comment] 2019-02-06 14:42
We tested this issue independently. It's released and stable.

**Comment by martindekov** [comment] 2019-03-15 21:26
I think I am still getting error in the official cloud.

https://system.o6s.io/dashboard/kenfdev

https://system.o6s.io/dashboard/KENFDEV

Is that due to the official cloud having older version of the dashboard?

**Comment by LucasRoesler** [comment] 2019-03-16 16:29
I am not seeing any explicit errors, but it is different

Lowercase:
![image](https://user-images.githubusercontent.com/891889/54478319-03fbfa80-4811-11e9-9354-b93644657c0a.png)


Uppercase:
![image](https://user-images.githubusercontent.com/891889/54478322-0c543580-4811-11e9-892a-caa46588f6c0.png)
